### ISSUE TITLE
Build fails for generator "Visual Studio 11 2012"

### ISSUE THREAD

**Issue by Knitschi** [hunter-packages/googletest#19]
I think it should be possible to build with Visual Studio 2012.

**Comment by Knitschi** [comment]
Does anybody know how I can compile with Visual Studio 2012? It looks like I have the compiler under `C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin`, but when I call `vcvarsall.bat x86` I get errors and the `VS110COMNTOOLS` environment variable is misteriously unset.

I tried to download **Visual Studio Express 2012** from the microsoft page, but the page seems to be buggy, it does not stop reloading and hitting the download links does nothing.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
