### ISSUE TITLE
Build failing in Hunter for 1.8.0-p9

### ISSUE THREAD

**Issue by xsacha** [hunter-packages/googletest#24]
It is providing this output when compiling GTest:

[cxxnode] [AWS CodeBuild Plugin] CMake Error at googletest/cmake/internal_utils.cmake:350 (if):
[cxxnode] [AWS CodeBuild Plugin]   if given arguments:
[cxxnode] [AWS CodeBuild Plugin] 
[cxxnode] [AWS CodeBuild Plugin]     "3.5.1" "VERSION_GREATER_EQUAL" "3.1.0"
[cxxnode] [AWS CodeBuild Plugin] 
[cxxnode] [AWS CodeBuild Plugin]   Unknown arguments specified
[cxxnode] [AWS CodeBuild Plugin] Call Stack (most recent call first):
[cxxnode] [AWS CodeBuild Plugin]   googletest/cmake/internal_utils.cmake:339 (install_pdb_files)
[cxxnode] [AWS CodeBuild Plugin]   googletest/CMakeLists.txt:102 (add_install_rules)

I see this in the CMake 3.7 release notes:

The if() command gained new boolean comparison operations LESS_EQUAL, GREATER_EQUAL, STRLESS_EQUAL, STRGREATER_EQUAL, VERSION_LESS_EQUAL, and VERSION_GREATER_EQUAL.****

So the check if version greater than 3.1 actually will never work in its expected manner.

**Comment by ruslo** [comment]
The fix is trivial as far as I understand, please send pull request.

**Comment by Knitschi** [comment]
I will handle this. I will replace it with `NOT 3.5.1 VERSION_LESS 3.1.0`

**Comment by Knitschi** [comment]
I created a pull request  #25

**Comment by ruslo** [comment]
Release with fixes: https://github.com/ruslo/hunter/releases/tag/v0.19.155
