### ISSUE TITLE
Build at 1.8.0-hunter-p11 fails due to Werror=deprecated-copy

### ISSUE THREAD

**Issue by Pascal-So** [hunter-packages/googletest#27]
After encountering errors in projects that use googletest via hunter, I noticed that the same error also occurs when I build the code from this repo at the release 1.8.0-hunter-p11 (commit d78baba0cc750201ee40429bc3959430c8181b91).

My system:
cmake 3.14.5
g++ 9.1.0
GNU Make 4.2.1

Steps to reproduce:
```bash
git checkout d78baba0cc750201ee40429bc3959430c8181b91
mkdir build
cd build
cmake ..
make
```

This is the first error that occurs:
```
[ 18%] Building CXX object googlemock/CMakeFiles/gmock_main.dir/src/gmock-all.cc.o
In file included from /home/pascal/code/googletest/googlemock/include/gmock/gmock-spec-builders.h:75,
                 from /home/pascal/code/googletest/googlemock/include/gmock/gmock-generated-function-mockers.h:43,
                 from /home/pascal/code/googletest/googlemock/include/gmock/gmock.h:61,
                 from /home/pascal/code/googletest/googlemock/src/gmock-all.cc:40:
/home/pascal/code/googletest/googlemock/include/gmock/gmock-matchers.h: In instantiation of ‘testing::PolymorphicMatcher<Impl>::PolymorphicMatcher(const Impl&) [with Impl = testing::internal::StrEqualityMatcher<std::__cxx11::basic_string<char> >]’:
/home/pascal/code/googletest/googlemock/include/gmock/gmock-matchers.h:497:10:   required from ‘testing::PolymorphicMatcher<Impl> testing::MakePolymorphicMatcher(const Impl&) [with Impl = testing::internal::StrEqualityMatcher<std::__cxx11::basic_string<char> >]’
/home/pascal/code/googletest/googlemock/include/gmock/gmock-matchers.h:3975:65:   required from here
/home/pascal/code/googletest/googlemock/include/gmock/gmock-matchers.h:432:67: error: implicitly-declared ‘testing::internal::StrEqualityMatcher<std::__cxx11::basic_string<char> >::StrEqualityMatcher(const testing::internal::StrEqualityMatcher<std::__cxx11::basic_string<char> >&)’ is deprecated [-Werror=deprecated-copy]
  432 |   explicit PolymorphicMatcher(const Impl& an_impl) : impl_(an_impl) {}
      |                                                                   ^
In file included from /home/pascal/code/googletest/googletest/include/gtest/internal/gtest-linked_ptr.h:74,
                 from /home/pascal/code/googletest/googlemock/include/gmock/internal/gmock-port.h:53,
                 from /home/pascal/code/googletest/googlemock/include/gmock/internal/gmock-generated-internal-utils.h:44,
                 from /home/pascal/code/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:45,
                 from /home/pascal/code/googletest/googlemock/include/gmock/gmock-actions.h:46,
                 from /home/pascal/code/googletest/googlemock/include/gmock/gmock.h:58,
                 from /home/pascal/code/googletest/googlemock/src/gmock-all.cc:40:
/home/pascal/code/googletest/googletest/include/gtest/internal/gtest-port.h:908:8: note: because ‘testing::internal::StrEqualityMatcher<std::__cxx11::basic_string<char> >’ has user-provided ‘void testing::internal::StrEqualityMatcher<StringType>::operator=(const testing::internal::StrEqualityMatcher<StringType>&) [with StringType = std::__cxx11::basic_string<char>]’
  908 |   void operator=(type const &)
      |        ^~~~~~~~
/home/pascal/code/googletest/googlemock/include/gmock/gmock-matchers.h:1180:3: note: in expansion of macro ‘GTEST_DISALLOW_ASSIGN_’
 1180 |   GTEST_DISALLOW_ASSIGN_(StrEqualityMatcher);
      |   ^~~~~~~~~~~~~~~~~~~~~~
```
... plus another 100 or so lines of similar errors.

I noticed that the code compiles fine at the top of the hunter-1.8.1 branch (currently 2fe3bd994b3189899d93f1d5a881e725e046fdc2). Are there any plans to publish a new release soon?

Also, I'm quite new to using hunter, so if you think I might be misunderstanding something about the hunter workflow then feel free to tell me.

**Comment by ruslo** [comment]
> I noticed that the code compiles fine at the top of the hunter-1.8.1 branch (currently 2fe3bd9). Are there any plans to publish a new release soon?

`hunter-1.8.1` is currently equal to upstream `v1.8.1` release. Feel free to send patches from the previous version. They are in branch `hunter`:
- https://github.com/hunter-packages/googletest/commits/hunter

See also:
- https://docs.hunter.sh/en/latest/creating-new/patch.html

**Comment by Pascal-So** [comment]
I'm not sure if I got this correctly what you're saying, but as it looks to me, the branch `hunter-1.8.1` doesn't need any patches, that one works as is.

When I include this repo at the `hunter-1.8.1` branch as a submodule and use `GIT_SUBMODULE external/googletest` in my `cmake/Hunter/config.cmake` of the project that relies on googletest, then the build works without any problems.

Therefore I think it should be fine to make a release from the `hunter-1.8.1` branch in its current state and add it to a new snapshot in your ruslo/hunter repository. If you want I can create a pull request to ruslo/hunter for updating the googletest package according to [this documentation](https://docs.hunter.sh/en/latest/creating-new/update.html), but I don't have the rights to create a release of 1.8.1 here in this repo.

**Comment by ruslo** [comment]
> the branch hunter-1.8.1 doesn't need any patches, that one works as is

> Therefore I think it should be fine to make a release from the hunter-1.8.1 branch in its current state and add it to a new snapshot in your ruslo/hunter repository

In this case, there is no need to use this fork. Use upstream release URL:
- https://github.com/google/googletest/archive/release-1.8.1.tar.gz

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
