### ISSUE TITLE
Release for googletest 1.8.1

### ISSUE THREAD

**Issue by Honeybunch** [hunter-packages/googletest#28]
I see that googletest 1.8.1 has been merged into this hunterized repo but there doesn't seem to be a 1.8.1 release. Is there anything preventing a release? I'd appreciate it as it fixes a bug with MSVC's C++17 support :)

**Comment by ruslo** [comment]
> I see that googletest 1.8.1 has been merged into this hunterized repo but there doesn't seem to be a 1.8.1 release.

Current `hunter-1.8.1` branch is equal to upstream `v1.8.1` tag.

> Is there anything preventing a release?

Somebody has to port patches from previous branch `hunter` to branch `hunter-1.8.1`:
- https://github.com/hunter-packages/googletest/commits/hunter

If these patches not needed the upstream release can be used. Package update instruction is here:
- https://docs.hunter.sh/en/latest/creating-new/update.html

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
