### ISSUE TITLE
Hunter integration

### ISSUE THREAD

**Issue by ruslo** [hunter-packages/googletest#3]
@Knitschi I'll add some issues we need to solve before this version of GTest can be integrated into Hunter instead of old one.
1. ~~We need to add `gtest_force_shared_crt=YES` to build arguments because playing with `MT`/`MD` flags break default linking configuration: https://github.com/hunter-packages/googletest/blob/32fa2e1010e700c17586708a74da0a50e7fa0b3b/googletest/cmake/internal_utils.cmake#L35
   This can be done by adding `hunter_cmake_args` to `GTest/hunter.cmake`. See [wiki](https://github.com/ruslo/hunter/wiki/usr.adding.new.package#cmake-options).~~
2. ~~I've tried to build current version of GTest with Visual Studio 8 2005 and I've got build errors: https://gist.github.com/ruslo/703ae20b5b2fe2a74af2 Old version https://github.com/hunter-packages/gtest/releases/tag/v1.7.0-hunter-11 works fine with this generator so we need to find workaround or version that works or make a fix.~~ use old version
3. ~~Same with MinGW: https://gist.github.com/ruslo/f98bd5cdcd9052d4823e Working version for old repository: https://github.com/hunter-packages/gtest/releases/tag/v1.7.0-hunter-6~~ use old version
4. ~~I've made a list of patches that need to be integrated into this version (probably re-test needed too):~~
   - https://github.com/hunter-packages/gtest/commit/cfdab358137fa9d3d281e00338926b26eecceeec
   - https://github.com/hunter-packages/gtest/commit/1a36780ee52977bbf85acddd258e114a1f9d3b27 (see http://stackoverflow.com/a/23326594/2288008)
   - https://github.com/hunter-packages/gtest/commit/0fc0224d55bbb5c8c89629a9c3b2f58f4118afa7
   - https://github.com/hunter-packages/gtest/commit/afc42c17489621787bf9414a206a9e66e8a8f9ce
   - https://github.com/hunter-packages/gtest/commit/fbefbd5f6fa9aece6e571a7e8b12037a14bef140

**Comment by Knitschi** [comment]
I can do it.

**Comment by Knitschi** [comment]
1. and 4. are resolved with that merge. Now I will install the vs-8-2005 and MinGW toolchain to make the rest work.

**Comment by ruslo** [comment]
> Now I will install the vs-8-2005 and MinGW toolchain to make the rest work

@Knitschi great, thanks

**Comment by Knitschi** [comment]
GoogleTest does currently not compile with MinGW. I get the same build errors as in this issue google/googletest#484
I will not try to fix this myself.

**Comment by ruslo** [comment]
> I will not try to fix this myself

There is no need to do the fix if it's not trivial, we just need to find some old version that works. If there is no easy way to determine what version was working in new repository we can use release from old repository https://github.com/hunter-packages/gtest/releases/tag/v1.7.0-hunter-6

**Comment by Knitschi** [comment]
You mean by using something like this in the default.cmake file?

```
if(MINGW)
  hunter_config(GTest VERSION 1.7.0-hunter-6)
else()
  hunter_config(GTest VERSION 1.8.0-hunter-p1)
endif()
```

**Comment by ruslo** [comment]
> You mean by using something like this in the default.cmake file?

Yep. Note that this will mean that there will be no GMock support for MinGW.

**Comment by Knitschi** [comment]
Where is the correct place to document that? In the Readme.md of the new GoogleTest package?

I now tried to install vs-8-2005 on windows 7 but I get "compatibility issues" warnings from windows when CMake does its compiler tests and the compiler tests fail. I do not have an Windows XP machine left where I could try to do it.

So I will not make that work either. I think there shouldn't be too many codebases out there the still require vs-8-2005 and also use gtest.

I will now make a new release and then add the necessary changes to hunter.

**Comment by ruslo** [comment]
> Where is the correct place to document that?

wiki page: https://github.com/ruslo/hunter/wiki/pkg.gtest

> So I will not make that work either

Same as MinGW then, we will use old version

> I think there shouldn't be too many codebases out there the still require vs-8-2005 and also use gtest

May be I will agree with that for other packages but GTest is the first package example that user will see and try when reading Hunter README (See `Tiny project with GTest`): https://github.com/ruslo/hunter#first-step so it's important that everything "just work".

**Comment by Knitschi** [comment]
Ok I changed the hunter config.cmake to use the old version if MSVC80 is used. I will shortly make a pull request for hunter.

**Comment by ruslo** [comment]
Linux error with CMake 3.4.1:

```
CMake Error at googletest/CMakeLists.txt:82 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "gtest_main".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * googletest/cmake/internal_utils.cmake:155 (target_link_libraries)
```

**Comment by Knitschi** [comment]
I read some CMake documentation and found:
[You can not mix target_link_libraries() calls that use the PUBLIC/PRIVATE keyword with calls that do not use it](https://cmake.org/cmake/help/v3.0/policy/CMP0023.html)

-> So I think I should add a keyword to the call in googletest/CMakeLists.txt:82
Should I use PRIVATE or PUBLIC? 

Some from the documentation [here](https://cmake.org/cmake/help/v3.4/manual/cmake-buildsystem.7.html#target-usage-requirements) in the section **Transitive Usage Requirements** I take, that I should use PUBLIC if the interface of gtest_main uses types from gtest. I should use PRIVATE if gtest is only used in the implementation of gtest_main.

I am not sure, but I think I should use PUBLIC linking because afaik gtest_main only adds a main() function and the client will use the gtest interface and not the gtest_main interface.

But also I wonder why I do not get that error when I run CMake on Windows?

**Comment by ruslo** [comment]
re:{But also I wonder why I do not get that error when I run CMake on Windows?} may be version is different? You can create [SSCCE](http://www.abbreviations.com/SSCCE) and if error message differs for different platforms probably you can try to report an issue.

**Comment by Knitschi** [comment]
I also have 3.4.1. To create an SSCCE I would need an Linux toolchain to build the same thing. I do not have that right now. Maybe I will find the time to set one up in the next weeks.

**Comment by ruslo** [comment]
Merged in https://github.com/ruslo/hunter/pull/306. Closing.
