### ISSUE TITLE
Visual Studio .pdb files missing.

### ISSUE THREAD

**Issue by Knitschi** [hunter-packages/googletest#7]
The folder $HUNTER_ROOT/_Base/xxxxxx/xxxxxx/xxxxxx/Install/lib does not contain the .pdb debugging information files for the Visual Studio toolchain.

This causes the warning **LNK4099** and debugging into the gtest cpp files is not possible.

**Comment by ruslo** [comment]
I think this feature is not supported in CMake by default. Also it's not related to "hunterization" so you can open same bug for the upstream: https://github.com/google/googletest

**Comment by Knitschi** [comment]
I looked a littele closer into this and it seems to be at some part at least a problem of wrong visual studio settings.

I managed to solve the problem manually by doing the following steps.
- Open the gmock.sln of the hunter/GoogleTest project
- Do for all projects: set _Properites_ -> _C/C++_ -> _Output Files_ -> _Program Database File Name_ to **$(OutDir)$(TargetName).pdb**. Now compiling the solution will create <targetname>.pdb files for all libs.
- Copy all the <targetname>.pdb files to **$HUNTER_ROOT/_Base/xxxxxx/xxxxxx/xxxxxx/Install/lib** folder
- Open my hunter "client" solution.
- Set the following properties of the text.exe target that causes the warnings: 
- _C/C++_ -> _Output Files_ -> _Program Database File Name_ to **$(OutDir)$(TargetName).pdb**
- _Linker_ -> _Debugging_ -> _Generate Program Database File_ to **$(OutDir)$(TargetName).pdb**

But now I see that this removes the warning, but debugging into the gtest code is still not possible. So not the right fix.

**Comment by ruslo** [comment]
Never work closer with `*.pdb` stuff. I think OpenCV do install `*.pdb` files. If you want you can take a look at the CMake code here: https://github.com/hunter-packages/opencv

**Comment by Knitschi** [comment]
Version 1.8.0-hunter-p5 fixed the issue.
