### ISSUE TITLE
GTest fails to build with MinGW

### ISSUE THREAD

**Issue by andoks** [hunter-packages/googletest#9]
Upstream bug https://github.com/google/googletest/issues/708

May be resolved when a release/build containing https://github.com/google/googletest/commit/ed9d1e1ff92ce199de5ca2667a667cd0a368482a is imported.

**Comment by ruslo** [comment]
@andoks Can you cherry-pick it and push to `hunter` branch?

**Comment by andoks** [comment]
I cherry-picked the two commits that are supposed to fix the bug in https://github.com/andoks/googletest/tree/hunter

**Comment by ruslo** [comment]
Can you create pull request?
